import type { Metadata } from "next";
import "./globals.css";
import { PhoneViewportFrame } from "./_client/PhoneViewportFrame";

export const SIDE_BG_COLOR = "#1C1D22";
export const SIDE_FG_COLOR = "#20232D";
export const MIDDLE_BG_COLOR = "#0E0F11";

export const metadata: Metadata = {
  title: "Bathhub Beta",
  description: "Generated by my brain",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const sideBg = SIDE_BG_COLOR;
  const sideFg = SIDE_FG_COLOR;
  const middleBg = MIDDLE_BG_COLOR;
  const gridSizePx = 28;

  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body
        className="flex items-center justify-center overflow-hidden"
        style={{
          backgroundColor: sideBg,
          backgroundImage: `
            linear-gradient(${sideFg} 1px, transparent 1px),
            linear-gradient(90deg, ${sideFg} 1px, transparent 1px)
          `,
          backgroundSize: `${gridSizePx}px ${gridSizePx}px`,
          height: "100dvh",
          width: "100vw",
        }}
      >
        <PhoneViewportFrame backgroundColor={middleBg}>
          {children}
        </PhoneViewportFrame>
      </body>
    </html>
  );
}
